dist: bionic
language: c++
before_install:
    - sudo add-apt-repository -y ppa:tobydox/mingw-w64
    - sudo apt update
    - sudo apt -y install sdl2-mingw-w64
    
addons:
  apt:
    packages:
      - build-essential
      - linux-libc-dev
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - gcc-7-multilib
      - gcc-aarch64-linux-gnu
      - gcc-powerpc-linux-gnu
      - libc6-arm64-cross
      - libc6-powerpc-cross
      - libc6-dev-arm64-cross
      - libc6-dev-powerpc-cross
      - g++-9
      - lcov
      - mingw-w64
      - gcc-mingw-w64-x86-64 
      - g++-mingw-w64-x86-64
      - libogg-dev
      - tree
      - libsndio-dev
      - libvorbis-dev
      - libopenal-dev
      - wine
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev

os:
    - linux

compiler:
    - g++

script:
    - travis/linux.sh
    - travis/windows.sh
